### PR TITLE
Background update refresh customization

### PR DESCRIPTION
**Pull request by xezrunner**
- [x] Load arbitrary update values from storage
- [x] Verify update period with different values
- [x] Verify / implement dynamic alarm period change
- [x] Settings UI for configuring period
  - [x] Design tweaks

### CODE REVIEW

**Comment by yungsamd17** [comment]
borked search
image

and color input
dQCCTMCm3Q

**Comment by xezrunner** [comment]
> borked search

Good catch! Wasn't sure whether the input style was broken / WIP on this branch. Looks like you took care of it already.

**Review by yungsamd17 — COMMENTED** [review]
👍

**Review by yungsamd17 — COMMENTED** [review]
.

**Pull request merged**
